"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

type Letter = { id:string; recipient:string; tags:string[]; body:string; released:boolean; created_at:string; updated_at:string };
type Memory = { id:string; body:string; created_at:string };

const prompts = [
  ["Missing & Remembering", "Today I am really missing…", "One ordinary moment I miss is…", "My happiest memory of you is…", "Something they always used to say was…", "I still laugh when I remember…"],
  ["Emotions & the experience of grief", "Right now, grief feels like…", "I’ve been feeling…", "The hardest time of day is…", "What no one sees is…", "How has my grief changed over time?"],
  ["Unfinished business & connection", "This is what I have to say to you…", "What I wish I had said or done differently…", "The goodbye I didn’t get to say…", "What would they say to me right now?"],
  ["Meaning, legacy & moving forward", "What did they teach me about how to live?", "What am I carrying forward?", "I can honor them by…", "What permission am I giving myself now?"],
];

function Auth(){
  const [mode,setMode]=useState<"login"|"signup">("login"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  if(!supabase) return <div className="auth"><div className="authbox"><h1>Letters to Heaven</h1><p className="sub">A quiet place for what remains.</p><div className="notice">Production configuration is not connected yet. Add the Supabase environment variables to Vercel to enable accounts and private storage.</div></div></div>;
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{if(mode==="signup"){const {error}=await supabase.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)throw error;setError("Check your email to confirm your account, then sign in.");}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}}catch(err){setError(err instanceof Error?err.message:"Something went wrong.");}finally{setBusy(false)}}
  return <main className="auth"><div className="authbox"><div className="brand" style={{justifyContent:"center"}}><span className="mark">✦</span><div><h1 style={{margin:0}}>Letters to Heaven</h1><p>A quiet place for what remains</p></div></div><div className="card" style={{marginTop:28}}><h3>{mode==="login"?"Welcome back":"Create your private space"}</h3><p className="desc">Your letters and memories belong to your account and are protected by database row-level security.</p><form onSubmit={submit}>{mode==="signup"&&<><label className="label">Name</label><input className="input" value={name} onChange={e=>setName(e.target.value)} autoComplete="name" /></>}<label className="label">Email</label><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" /><label className="label">Password</label><input className="input" type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="login"?"current-password":"new-password"}/>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy} style={{width:"100%",marginTop:12}}>{busy?"Please wait…":mode==="login"?"Enter your space":"Create account"}</button></form><button className="secondary" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("")}} style={{width:"100%",marginTop:10}}>{mode==="login"?"Create an account":"I already have an account"}</button></div></div></main>
}

export default function Home(){
  const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{if(!supabase){setLoading(false);return;}supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
  if(loading)return <div className="auth"><div className="authbox"><h1>Letters to Heaven</h1><p className="sub">Opening your private space…</p></div></div>;
  if(!user)return <Auth/>;
  return <App user={user}/>;
}

function App({user}:{user:User}){
  const [tab,setTab]=useState("write"); const [letters,setLetters]=useState<Letter[]>([]); const [memories,setMemories]=useState<Memory[]>([]); const [recipient,setRecipient]=useState(""); const [tags,setTags]=useState(""); const [body,setBody]=useState(""); const [memory,setMemory]=useState(""); const [message,setMessage]=useState(""); const [selected,setSelected]=useState<Letter|null>(null); const [saving,setSaving]=useState(false);
  const load=async()=>{if(!supabase)return;const [l,m]=await Promise.all([supabase.from("letters").select("*").order("updated_at",{ascending:false}),supabase.from("memories").select("*").order("created_at",{ascending:false})]);if(l.data)setLetters(l.data);if(m.data)setMemories(m.data)};
  useEffect(()=>{load()},[]);
  const displayName=useMemo(()=>user.user_metadata?.display_name||user.email?.split("@")[0]||"friend",[user]);
  function toast(t:string){setMessage(t);window.setTimeout(()=>setMessage(""),2500)}
  async function saveLetter(){if(!supabase||!recipient.trim()||!body.trim())return;setSaving(true);const {data,error}=await supabase.from("letters").insert({user_id:user.id,recipient:recipient.trim(),tags:tags.split(",").map(x=>x.trim()).filter(Boolean),body:body.trim()}).select().single();setSaving(false);if(error){toast(error.message);return}setLetters(x=>[data,...x]);setRecipient("");setTags("");setBody("");toast("Your letter has been kept private.");setTab("vault")}
  async function addMemory(){if(!supabase||!memory.trim())return;const {data,error}=await supabase.from("memories").insert({user_id:user.id,body:memory.trim()}).select().single();if(error){toast(error.message);return}setMemories(x=>[data,...x]);setMemory("");toast("Memory placed in the jar.")}
  async function deleteMemory(id:string){if(!supabase)return;await supabase.from("memories").delete().eq("id",id);setMemories(x=>x.filter(m=>m.id!==id))}
  async function candle(letter:Letter){if(!supabase)return;await supabase.from("candle_lights").insert({user_id:user.id,letter_id:letter.id});toast("A candle is lit.")}
  async function release(letter:Letter){if(!supabase)return;const {data,error}=await supabase.from("letters").update({released:!letter.released}).eq("id",letter.id).select().single();if(error){toast(error.message);return}setLetters(x=>x.map(l=>l.id===letter.id?data:l));setSelected(data);toast(data.released?"Marked as released for your records.":"Returned to private.")}
  const nav=["write","prompts","memories","vault"];
  return <main className="shell"><header className="top"><div className="brand"><span className="mark">✦</span><div><h1>Letters to Heaven</h1><p>A quiet place for what remains</p></div></div><button onClick={()=>supabase?.auth.signOut()}>Sign out</button></header><section className="hero"><h2>Keep what matters close.</h2><p>Write freely. Remember gently. This space is yours, {displayName}. Your private entries are stored under your account and protected by row-level security.</p></section><nav className="nav">{nav.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>{setTab(x);setSelected(null)}}>{x==="write"?"Write":x==="prompts"?"Journaling Prompts":x==="memories"?"Memory Jar":"Vault"}</button>)}</nav>
  {tab==="write"&&<section className="card"><h3>Write a letter</h3><p className="desc">Address it to someone you love and miss. Say what needs saying — unfinished words, updates, gratitude, anger, or simply “I remember.”</p><div className="notice">There is no right or wrong way to write. Messy, short, long, angry, tender — all of it belongs here.</div><label className="label">To</label><input className="input" placeholder="Mom, Dad, Grandma June, my dear friend…" value={recipient} onChange={e=>setRecipient(e.target.value)}/><label className="label">Tags</label><input className="input" placeholder="gratitude, birthday, anniversary, memory…" value={tags} onChange={e=>setTags(e.target.value)}/><label className="label">Your letter</label><textarea className="textarea" placeholder="Dear…" value={body} onChange={e=>setBody(e.target.value)}/><div className="row"><button className="primary" disabled={saving||!recipient.trim()||!body.trim()} onClick={saveLetter}>{saving?"Keeping…":"Keep this letter"}</button><button className="secondary" onClick={()=>{setRecipient("");setTags("");setBody("")}}>Clear</button></div></section>}
  {tab==="prompts"&&<section className="card"><h3>Grief journaling prompts</h3><p className="desc">Choose a prompt that resonates today. Skip anything that feels too tender.</p>{prompts.map(([title,...items])=><div key={title} style={{marginBottom:24}}><div className="label">{title}</div><div className="grid">{items.map(p=><button className="prompt" key={p} onClick={()=>{setBody(p+"\n\n");setTab("write")}}>{p}</button>)}</div></div>)}</section>}
  {tab==="memories"&&<section className="card"><h3>Memory Jar</h3><p className="desc">Gather small, ordinary, and precious memories so they don’t fade. You can return and add more anytime.</p><div className="row"><input className="input" style={{flex:1,minWidth:220}} placeholder="A small thing I remember…" value={memory} onChange={e=>setMemory(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addMemory()}}/><button className="primary" onClick={addMemory}>Place in the jar</button></div><div style={{marginTop:20}}>{memories.length?memories.map(m=><div className="letter" key={m.id} style={{marginBottom:8}}><div className="preview">{m.body}</div><div className="row" style={{justifyContent:"space-between",marginTop:8}}><span className="meta">{new Date(m.created_at).toLocaleDateString()}</span><button className="secondary" onClick={()=>deleteMemory(m.id)}>Remove</button></div></div>):<div className="empty">Your jar is waiting for its first memory.</div>}</div></section>}
  {tab==="vault"&&<section className="card"><h3>Your Vault</h3><p className="desc">Letters you’ve kept close. Private by default. Revisit one whenever you need to.</p>{selected?<><button className="secondary" onClick={()=>setSelected(null)}>← Back to Vault</button><div style={{marginTop:20}}><div className="letter"><div className="to">To {selected.recipient}</div><div className="meta">{new Date(selected.created_at).toLocaleString()}</div><div className="letter .preview" style={{whiteSpace:"pre-wrap",font:"20px/1.8 Georgia,serif",color:"var(--text)",marginTop:18}}>{selected.body}</div>{selected.tags?.map(t=><span className="tag" key={t}>{t}</span>)}<div className="row" style={{marginTop:20}}><button className="primary" onClick={()=>candle(selected)}>✦ Light a candle</button><button className="secondary" onClick={()=>release(selected)}>{selected.released?"Return to private":"Release this letter"}</button></div></div></div></>:letters.length?<div style={{display:"grid",gap:10}}>{letters.map(l=><button className="letter" style={{textAlign:"left"}} key={l.id} onClick={()=>setSelected(l)}><div className="to">To {l.recipient}</div><div className="meta">{new Date(l.updated_at).toLocaleString()} · {l.released?"Released":"Private"}</div><div className="preview">{l.body}</div>{l.tags?.map(t=><span className="tag" key={t}>{t}</span>)}</button>)}</div>:<div className="empty"><div style={{fontSize:36}}>✦</div>Your vault is quiet for now.<br/>When you’re ready, write your first letter.</div>}</section>}
  <div className="footer">Private by default · Your writing belongs to you · Letters to Heaven</div>{message&&<div style={{position:"fixed",bottom:24,left:"50%",transform:"translateX(-50%)",background:"var(--card)",border:"1px solid var(--gold)",padding:"11px 16px",borderRadius:999,zIndex:20}}>{message}</div>}</main>
}
